<!--
  This file creates the book details page and queries the PostgreSQL database for book info. Please DO NOT EDIT this file!

  Since it turns out that .js doesn't really work for querying and sending data between a server and a website, 
  we will be having to use .php for our project going forward. 


  You MUST be connected to your Apache localhost:3300 server from XAMPP in
  order this .php for this to work.



  Use .php pages instead of .html pages since this lets you communicate with the server.
      .js files are used for running external scripts inside your .php page. 
        Any scripts should be loaded at the very end of the </body> tag, Like <script></script> </body>

  I included jQuery into our filesystem since it helps with AJAX (javascript function to help pages load content without having to refresh)
  and other features you might find helpful.



  >>To connect your webpage to the database, and include jQuery you MUST include the database connect script at the top of the code!<<



  --------------------------------------------------------------------------------------------------------

  How to get a webpage to change depending on URL parameters?

  When testing this bookdetails.php page, you'd notice that the URL comes back as: http://localhost:3300/book/bookdetails.php?book=1
  

  Breaking down this URL:
     http://localhost:3300/ connects you to a localhost server running our website
     /book/ is this folder, which can be accessed on the website to open .php files inside it
     bookdetails.php, is this .php page
     ?book=1 is a parameter that connects to the book.book_id column on the db
              When you put in a number other than 1, it changes the content on the page

  You can use parameters like ?book=1 to pass variables between PHP and the database.

  For example, if I was making a search feature, and I typed 'dog' into the search bat
  I can have the search bar send back a response of http://localhost:3300/search/searchresults.php?title=dog
  --------------------------------------------------------------------------------------------------------

  SQL Cheat Sheet

  Bookstore database schema diagram (needs to be updated since I added some new tables): https://drive.google.com/file/d/1dceGphBRJ8rwF6NTeobnqxH4BSAOG1ek/view?usp=sharing

  Queries to the database come back with a response you can use in your page.

  A sample query is: "SELECT book_id FROM book WHERE $book_id" which gets the book ids from the book table, for whatever the value of the $book_id variable is
  Breaking this down:
    SELECT means to grab or get data from the db.
      book_id is a column in the book table
    FROM means what table to get the data from
      book is a table in the db
    WHERE specifies an argument for the query. Like book_id > 2 would return book_id values that are less than 2.
      $book_id is a php variable you can define in a php script. I define this below inside my code using a $_GET function 
      to get a paramater from the URL
  
  Some Query Keywords:
  SELECT- grabs values from db
  FROM- specifies table
  WHERE- specifies argument for query
  * - wildcard value, can be used like SELECT * which would grab all values in a table
  JOIN - joins two or more tables
  IN specifies multiple arguments for query 
  ORDER BY ASC/DESC orders values by either ascending or descending order
  --------------------------------------------------------------------------------------------------------

  Here's a sample of how to get your php webpage to display a query in text (remove the . infront of ?php):
  
  <.?php
    $result = pg_query($con, " SELECT title FROM book WHERE book_id = $book_id"); //Title query
    $row = pg_fetch_assoc($result); //Fetches the result as a raw array
    echo "$row[title]"; //Displays the result as a string for ptinting onto the webpage
  ?>

  Feel free to copy this code for your own features!
-->

<!--Copy everything between these tags for creating a new webpage-->
<?php
  include '../scripts/db.php' //Database connect script (put this at the top of your page)
?>

<!DOCTYPE HTML>
<html>
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="./css/style.css"> <!--Replace this with your own CSS file-->
  <script src="../scripts/jquery.js"></script>  <!--Includes JQuery-->
</head>
<!--End CopyPaste-->

<body>
  <?php
  $book_id = $_GET['book']; //This reads the ?book= parameter from the URL
  ?>
  <div class="content">
      <div id="first-half" class="half">
        <span class="parenth1">
          <?php
            $result = pg_query($con, " SELECT title FROM book WHERE book_id = $book_id"); //Title query
            $row = pg_fetch_assoc($result); //Fetches the result as a raw array
            echo "$row[title]"; //Displays the result as a string for printing onto the webpage
          ?>
          </span>
          <div class="subtitle">     </div>
          <div class="subtitle">
            <?php
            $result = pg_query($con, " SELECT publication_date FROM book WHERE book_id = $book_id");  //Date query
            $row = pg_fetch_assoc($result);
            $originalDate = "$row[publication_date]";
            $newDate = date("d-m-Y", strtotime($originalDate));
            echo $newDate;
            ?>  </div>
          <div class="subtitle">     </div>
          <div class="subtitle">0/5 Stars</div> <!--Rating average should be added here when feature is ready-->
        
      <h2> 
        by <?php //Look at this later, remember to update the db
            $result = pg_query($con, " SELECT author_id FROM book_author WHERE book_id = $book_id"); //Author query, clicking on author name returns search function link
            $row = pg_fetch_assoc($result);
            $author_id ="$row[author_id]";

            $result2 = pg_query($con, " ((SELECT author_name FROM author WHERE author_id = (SELECT author_id FROM book_author WHERE book_id = $book_id LIMIT 1)) ORDER BY author_id ASC);");
            $row = pg_fetch_assoc($result2);
            
            echo "<a href='search/searchresults.php?author_id=$author_id'>$row[author_name]</a>"; //Prints the author name as a clickable link to the search feature, using the author_id as a parameter

        ?></h2>
      <p><?php
            $result = pg_query($con, " SELECT genre FROM book WHERE book_id = $book_id"); //Genre query, clicking on genre name returns search function link
            $row = pg_fetch_assoc($result);
            $genre ="$row[genre]";
            $uppercase_genre = ucfirst($genre); 

            echo "<a href='search/searchresults.php?genre=$genre'>$uppercase_genre</a>"; 
          ?>
      <h2>   </h2>
        <div class="no-change">
          <p><?php 
            $result = pg_query($con, " SELECT descr FROM book WHERE book_id = $book_id"); //Description query
            $row = pg_fetch_assoc($result);
            echo "$row[descr]"; 
            ?></p>
        </div>
      <h2> </h2>
        <button class="accordion">Reviews</button>  <!--Reviews dropdown table for when reviews are implimented-->
          <div class="panel">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          </div>
      </div>
      <div id="second-half" class="half">
        <div class="book-cover">
        <img src="https://www.jimkarol.com/wp-content/uploads/2017/03/book.jpg" />  <!--Dummy image link (should we even include images for our books?) We'd have to pick them off google images or something-->
        </div>
        <div class="cart"><?php echo "<a href='/cart/cart.php?addbook=$book_id'>Add to Cart</a>" ?></div> <!--Buttons to send the book_id to the cart and wishlist features-->
        <div class="wishlist"><?php echo "<a href='/wishlist/wishlist.php?addbook=$book_id'>Add to Wish List</a>" ?></div>
        <h3>
          $<?php
            $result = pg_query($con, " SELECT price FROM order_line WHERE book_id = $book_id"); //Price query (we need to add more prices, descriptions, and genres for the books in the database, maybe for at least 30 books?)
            $row = pg_fetch_assoc($result);
            echo "$row[price]";
          ?></h3>
        <div class="parenth1">ISBN: <div class ="subtitle"><?php 
              $result = pg_query($con, " SELECT isbn13 FROM book WHERE book_id = $book_id"); //ISBN query
              $row = pg_fetch_assoc($result);
              echo "$row[isbn13]"; 
        ?></div></div>
        <div class="parenth1">Publisher: <div class ="subtitle"><?php 
              $result = pg_query($con, " SELECT publisher_name FROM publisher WHERE publisher_id = (SELECT publisher_id FROM book WHERE book_id = $book_id)"); //Publisher query
              $row = pg_fetch_assoc($result);
              echo "$row[publisher_name]"; 
        ?></div></div>
        <div class="parenth1">Books Sold: <div class ="subtitle"><?php 
              $result = pg_query($con, " SELECT copies_sold FROM book WHERE book_id = $book_id"); //Publisher query
              $row = pg_fetch_assoc($result);
              echo "$row[copies_sold]"; 
        ?></div></div>
      </div>
  </div>
  <script src="./f4scripts/resize.js"></script>
  <script src="./f4scripts/accordion.js"></script>

  </body>
</html>